### ISSUE TITLE
predict-eth2.md

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pm#179]
## Motivation

Ocean is focusing on DeFi, specifically DeFi traders, more specifically the Python-savvy data scientists doing algorithmic trading. Towards this, we have series of Data Bounties to predict ETH price. The [ocean.py predict-eth.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/predict-eth.md) README supported the first Data Bounty. The predict-eth2.md README will support the second. And so on.

We use these bounties, with key support from the READMEs - as the internal customer towards serving DeFi traders, to help us prioritize work across the Ocean stack, from Aquarius and Provider to ocean.py and ocean.js.

_This_ epic tees up for the second challenge.

Overall aim: reduce friction to competitors doing the challenge and getting better prediction results. For the second challenge, this includes showing a baseline approach to build a model from data feed(s), and providing more input data from a greater variety of sources. Future predict-eth READMEs will start to incorporate C2D.

## TODOs

Jaime:
- [ ] in eth predict challenge, do a simple model-based prediction (eg linear model from scikit learn). As part of this: write the code that uses just the 1 provided dataset. Put this into readme.
- [ ] change graphql readme: eth/usdt on TheGraph. Publish and consume 
- [ ] change smart contracts readme: eth/usdt on uniswap 
- [ ] publish asset: eth/usdt on TheGraph (graphql). update eth-predict2.md to also load it  
- [ ] publish asset: eth/usdt on uniswap (smart contract). Update eth-predict2.md to also load it 
- [ ] in eth predict challenge, improve model-based prediction. As part of this: write the code that merges all 3+ existing datasets. Put this into readme 

JP:
- [ ] publish asset: btc/usdt on Ocean CEXA. update eth-predict2.md to also load it  
- [ ] publish asset: btc/usdt on TheGraph (graphql). update eth-predict2.md to also load it  
- [ ] publish asset: btc/usdt on uniswap (smart contract). Update eth-predict2.md to also load it 
- [ ] in eth predict challenge, improve model-based prediction. As part of this: write the code that merges all 6+ existing datasets. Put this into readme
