### ISSUE TITLE
Move forward pwang project on LLM-licensing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pm#198]
### Background / motivation

See slack channel [#llm-license-peter-wang](https://oceanprotocol.slack.com/archives/C04Q881G82D)

### TODOs (WIP)
- [ ] Ensure data assets with LLM-friendly licenses can be published via ocean.py
- [ ] Make it easy to natively install ocean library in anaconda
- [ ] (Eventually) Have ocean.py as _pre-_ installed library in anaconda
- [ ] Create LLM-licensing tuned frontend dapp. 
  - Start as fork of Ocean Market
  - Ensure that LLM licence(s) can be used
  - Update branding 
  - What else?
