### ISSUE TITLE
Decentralized Backend Storage - phase2

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/pm#204]
To complete DBS, we need to implement the following:
- [ ] bundle in barge (Alex)
- [ ] create ipfs microservice
- [ ] Build new js library to interact with DBS (Jamie)
- [ ] Build UI components that uses js library to interact with DBS (Enzo)
- [ ] Build new py library to interact with DBS

**Comment by LoznianuAnamaria** [comment]
The uploader has been released in production
