### ISSUE TITLE
Deploy Ocean on Optimism

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/pm#208]
1. Deploy Ocean on Optimism Testnet

- [x] Check for free/commercial RPC
- [x] Deploy Ocean Token
- [x] Deploy contracts

2. Deploy Ocean on Optimism

- [x] Check for free/commercial RPC
- [x] Bridge Ocean from Ethereum to Optimism
- [x] Deploy contracts
- [x]  Update & deploy subgraph
- [x]  Update & deploy aquarius
- [x]  Update & deploy provider
- [x]  Update ocean.js
- [x]  Update ocean.py - https://github.com/oceanprotocol/ocean.py/issues/1502
- [x]  Update market
- [x]  Update status.oceanprotocol.com

**Comment by LoznianuAnamaria** [comment]
@mihaisc We need the deadlines for the activities covered in this issue.

**Comment by LoznianuAnamaria** [comment]
Blocked till the PR on OP is approved
